spring:
  cloud:
    # nacos config
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
#        namespace: 8c14ca1b-7519-469a-b9c9-37485813dd88
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/photo?zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: qaz147896325

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      auto:
        commit:
          interval:
            ms: 1000
      auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 20
      properties:
        group:
          id: defaultConsumerGroup
        request:
          timeout:
            ms: 180000
        session:
          timeout:
            ms: 120000
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false
    producer:
      acks: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger:
          ms: 0
      retries: 0
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  # name
  application:
    name: cloud-photo-image

server:
  port: 8089

#mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml

